"""The index mapping of the offline tests: batch job executions, one document per run."""

MAPPING = {'dynamic': 'strict',
 'properties': {'@timestamp_date': {'type': 'date'},
                'APPLICATION': {'type': 'keyword'},
                'POSITION_DATE': {'type': 'keyword'},
                'ENVIRONMENT_TYPE': {'type': 'keyword'},
                'CLASSIFICATION': {'type': 'keyword'},
                'RUN_MODE': {'type': 'keyword'},
                'ALL_DIMENSIONS': {'type': 'keyword'},
                'DIMENSION_1': {'type': 'keyword'},
                'DIMENSION_2': {'type': 'keyword'},
                'DIMENSION_3': {'type': 'keyword'},
                'ERROR_CATEGORY': {'type': 'keyword'},
                'ERROR_SUBCATEGORY': {'type': 'keyword'},
                'ERROR_DESCRIPTION': {'type': 'keyword'},
                'ERROR_EXCEPTION': {'type': 'text',
                                    'fields': {'keyword': {'type': 'keyword', 'ignore_above': 256}}},
                'SEVERITY': {'type': 'keyword'},
                'PRIORITY_d': {'type': 'double'},
                'STATUS_INFO': {'type': 'keyword'},
                'PROCESS_TYPE': {'type': 'keyword'},
                'SCOPE': {'type': 'keyword'},
                'ACTIVITY': {'type': 'keyword'},
                'BUSINESS_LINE': {'type': 'keyword'},
                'SUB_BUSINESS_LINE': {'type': 'keyword'},
                'REGION': {'type': 'keyword'},
                'SITE': {'type': 'keyword'},
                'JOB_EXEC_TYPE': {'type': 'keyword'},
                'RELAUNCHED': {'type': 'boolean'},
                'LONG_RUNNING': {'type': 'boolean'},
                'POOL': {'type': 'keyword'},
                'NODE': {'type': 'keyword'},
                'SEQUENCE_ID': {'type': 'keyword'},
                'PARAM_ID': {'type': 'keyword'},
                'RUN_ID': {'type': 'keyword'},
                'OUTPUT_PATH': {'type': 'keyword'},
                'LOCK_FLAG': {'type': 'keyword'},
                'JOB_DURATION_d': {'type': 'double'},
                'CPU_COST_H_d': {'type': 'double'},
                'MAX_JOBS_COUNT_d': {'type': 'double'},
                'TAGS': {'type': 'keyword'}}}
